In [46]:
# imports
from pathlib import Path

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import geopandas as gpd

In [47]:
lakes_data = Path.cwd().parent.joinpath('raw_data', 'lakes', 'lakes_us.shp')
lakes_data

PosixPath('/Users/khuenguyen/Desktop/team-nuclear-family/raw_data/lakes/lakes_us.shp')

In [48]:
county_data = Path.cwd().parent.joinpath('raw_data', 'county_boundaries_2025', 'tl_2025_us_county.shp')
county_data

PosixPath('/Users/khuenguyen/Desktop/team-nuclear-family/raw_data/county_boundaries_2025/tl_2025_us_county.shp')

In [49]:
df = gpd.read_file(lakes_data)
df.head()

,Hylak_id,Lake_name,Country,Continent,Poly_src,Lake_type,Grand_id,Lake_area,Shore_len,Shore_dev,...,Vol_src,Depth_avg,Dis_avg,Res_time,Elevation,Slope_100,Wshd_area,Pour_long,Pour_lat,geometry
0,5,Superior,United States of America,North America,SWBD,1,0,81843.92,5248.36,5.18,...,1,146.7,2869.953,48410.3,179,-1.0,209219.5,-84.460547,46.468593,"POLYGON ((-90.7225 46.6574, -90.72458 46.65783..."
1,6,Michigan,United States of America,North America,SWBD,1,0,57726.84,2862.67,3.36,...,1,84.2,1877.753,29956.0,175,-1.0,176006.4,-84.753910,45.822916,"POLYGON ((-84.75366 45.83889, -84.75365 45.783..."
2,7,Ontario,United States of America,North America,SWBD,3,1485,19347.36,2609.93,5.29,...,1,84.8,7745.819,2450.5,73,-1.0,766137.4,-75.794246,44.480557,"POLYGON ((-79.09167 43.81213, -79.09133 43.812..."
3,8,Huron,United States of America,North America,SWBD,1,0,59399.30,8856.64,10.25,...,1,59.8,9162.152,4484.5,175,-1.0,576017.7,-82.422576,42.999403,"POLYGON ((-80.99694 45.92284, -80.99838 45.921..."
4,9,Erie,United States of America,North America,SWBD,1,0,25767.79,1935.52,3.40,...,1,19.4,9796.883,589.5,172,-1.0,679903.4,-78.908084,42.904334,"POLYGON ((-83.34778 41.88395, -83.3484 41.8838..."

In [50]:
print(df.shape)
print(df.columns)
print(df.isnull().sum())

(104419, 22)
Index(['Hylak_id', 'Lake_name', 'Country', 'Continent', 'Poly_src',
       'Lake_type', 'Grand_id', 'Lake_area', 'Shore_len', 'Shore_dev',
       'Vol_total', 'Vol_res', 'Vol_src', 'Depth_avg', 'Dis_avg', 'Res_time',
       'Elevation', 'Slope_100', 'Wshd_area', 'Pour_long', 'Pour_lat',
       'geometry'],
      dtype='object')
Hylak_id          0
Lake_name    103389
Country           0
Continent         0
Poly_src          0
Lake_type         0
Grand_id          0
Lake_area         0
Shore_len         0
Shore_dev         0
Vol_total         0
Vol_res           0
Vol_src           0
Depth_avg         0
Dis_avg           0
Res_time          0
Elevation         0
Slope_100         0
Wshd_area         0
Pour_long         0
Pour_lat          0
geometry          0
dtype: int64

In [51]:
df["Lake_type"].unique()

array([1, 3, 2], dtype=int32)

In [52]:
df.crs

<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984 ensemble
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

In [53]:
df = df[["Hylak_id", "Lake_name", "Lake_area", "Vol_total", "Depth_avg", "Dis_avg", "geometry"]].to_crs(epsg = 5070)
df.columns = ["lake_id", "name", "area", "volume", "avg_depth", "avg_discharge", "geometry"]
df.head()

,lake_id,name,area,volume,avg_depth,avg_discharge,geometry
0,5,Superior,81843.92,12004000.0,146.7,2869.953,"POLYGON ((405138.62 2641010.425, 404976.847 26..."
1,6,Michigan,57726.84,4860000.0,84.2,1877.753,"POLYGON ((872497.203 2590661.212, 873227.595 2..."
2,7,Ontario,19347.36,1640000.0,84.8,7745.819,"POLYGON ((1347827.169 2433585.831, 1347852.003..."
3,8,Huron,59399.30,3550000.0,59.8,9162.152,"POLYGON ((1160360.641 2640079.646, 1160280.976..."
4,9,Erie,25767.79,499000.0,19.4,9796.883,"POLYGON ((1039502.066 2167229.056, 1039453.445..."

In [54]:
assert df["lake_id"].nunique() == len(df)

In [55]:
df_county = gpd.read_file(county_data)
print(df_county.shape)
df_county = df_county[["GEOID", "NAMELSAD", "geometry"]].rename(columns = {"GEOID": "geoid", "NAMELSAD": "county_name"})
df_county = df_county.to_crs(epsg = 5070)
df_county

(3235, 19)

,geoid,county_name,geometry
0,40075,Kiowa County,"POLYGON ((-267035.259 1343980.561, -266490.502..."
1,46079,Lake County,"POLYGON ((-71100.31 2327435.998, -71100.293 23..."
2,37033,Caswell County,"POLYGON ((1489331.21 1620697.325, 1489336.836 ..."
3,48377,Presidio County,"POLYGON ((-857749.848 879396.771, -857744.209 ..."
4,39057,Greene County,"POLYGON ((1008169.795 1915287.022, 1008161.905..."
...,...,...,...
3230,53065,Stevens County,"POLYGON ((-1634783.911 2949984.436, -1634792.5..."
3231,19177,Van Buren County,"POLYGON ((319198.812 1994179.49, 319368.793 19..."
3232,31073,Gosper County,"POLYGON ((-333884.885 1963990.326, -333876.567..."
3233,28095,Monroe County,"POLYGON ((712737.052 1232057.495, 712736.922 1..."
3234,12033,Escambia County,"POLYGON ((796753.93 900693.947, 796753.954 900..."

In [56]:
df_join = gpd.sjoin(df, df_county, predicate = "intersects", how = "left")
df_join.head()

,lake_id,name,area,volume,avg_depth,avg_discharge,geometry,index_right,geoid,county_name
0,5,Superior,81843.92,12004000.0,146.7,2869.953,"POLYGON ((405138.62 2641010.425, 404976.847 26...",2495.0,26033,Chippewa County
0,5,Superior,81843.92,12004000.0,146.7,2869.953,"POLYGON ((405138.62 2641010.425, 404976.847 26...",3187.0,26095,Luce County
0,5,Superior,81843.92,12004000.0,146.7,2869.953,"POLYGON ((405138.62 2641010.425, 404976.847 26...",3064.0,26003,Alger County
0,5,Superior,81843.92,12004000.0,146.7,2869.953,"POLYGON ((405138.62 2641010.425, 404976.847 26...",371.0,26103,Marquette County
0,5,Superior,81843.92,12004000.0,146.7,2869.953,"POLYGON ((405138.62 2641010.425, 404976.847 26...",1478.0,26013,Baraga County

In [58]:
joined = gpd.sjoin(df_county[["geoid", "county_name", "geometry"]], 
                   df, how="left", predicate="intersects")

lake_features = joined.groupby("geoid").agg(
    lake_count      = ("lake_id", "count"),
    total_lake_area = ("area", "sum"),
    avg_vol         = ("volume", "mean"),
    avg_depth       = ("avg_depth", "mean"),
    avg_discharge   = ("avg_discharge", "mean")
).reset_index()

# Merge back to county
df_county = df_county.merge(lake_features, on="geoid", how="left")
df_county[["lake_count", "total_lake_area", "avg_vol", "avg_depth", "avg_discharge"]] = \
    df_county[["lake_count", "total_lake_area", "avg_vol", "avg_depth", "avg_discharge"]].fillna(0)

# county centroids
df_county["centroid"] = df_county.centroid

In [59]:
df_county

,geoid,county_name,geometry,lake_count,total_lake_area,avg_vol,avg_depth,avg_discharge,centroid
0,40075,Kiowa County,"POLYGON ((-267035.259 1343980.561, -266490.502...",10,44.84,41.070000,3.410000,1.250700,POINT (-270070.971 1321674.415)
1,46079,Lake County,"POLYGON ((-71100.31 2327435.998, -71100.293 23...",48,45.55,3.010417,2.541667,0.158333,POINT (-90223.338 2337302.331)
2,37033,Caswell County,"POLYGON ((1489331.21 1620697.325, 1489336.836 ...",4,17.85,43.295000,6.875000,1.984750,POINT (1473665.516 1612333.443)
3,48377,Presidio County,"POLYGON ((-857749.848 879396.771, -857744.209 ...",0,0.00,0.000000,0.000000,0.000000,POINT (-793168.208 803695.173)
4,39057,Greene County,"POLYGON ((1008169.795 1915287.022, 1008161.905...",8,3.14,1.077500,2.712500,13.999125,POINT (1026417.426 1917896.79)
...,...,...,...,...,...,...,...,...,...
3230,53065,Stevens County,"POLYGON ((-1634783.911 2949984.436, -1634792.5...",27,303.67,248.890370,7.285185,134.215963,POINT (-1620086.769 3008995.813)
3231,19177,Van Buren County,"POLYGON ((319198.812 1994179.49, 319368.793 19...",5,2.34,1.660000,3.240000,0.107800,POINT (339024.413 1978577.566)
3232,31073,Gosper County,"POLYGON ((-333884.885 1963990.326, -333876.567...",4,12.42,33.357500,8.900000,0.023500,POINT (-321757.583 1951127.058)
3233,28095,Monroe County,"POLYGON ((712737.052 1232057.495, 712736.922 1...",12,20.16,6.275833,2.883333,22.639000,POINT (689723.121 1230229.636)
3234,12033,Escambia County,"POLYGON ((796753.93 900693.947, 796753.954 900...",4,2.06,2.297500,3.650000,0.378250,POINT (830688.592 865842.346)

In [66]:
lakes_combined = df.geometry.union_all()
df_county["dist_to_lakes_km"] = df_county["centroid"].apply(
    lambda x: x.distance(lakes_combined) / 1000
)

In [69]:
df_county

,geoid,county_name,geometry,lake_count,total_lake_area,avg_vol,avg_depth,avg_discharge,centroid,dist_to_lakes_km
0,40075,Kiowa County,"POLYGON ((-267035.259 1343980.561, -266490.502...",10,44.84,41.070000,3.410000,1.250700,POINT (-270070.971 1321674.415),4.537778
1,46079,Lake County,"POLYGON ((-71100.31 2327435.998, -71100.293 23...",48,45.55,3.010417,2.541667,0.158333,POINT (-90223.338 2337302.331),2.052128
2,37033,Caswell County,"POLYGON ((1489331.21 1620697.325, 1489336.836 ...",4,17.85,43.295000,6.875000,1.984750,POINT (1473665.516 1612333.443),2.538993
3,48377,Presidio County,"POLYGON ((-857749.848 879396.771, -857744.209 ...",0,0.00,0.000000,0.000000,0.000000,POINT (-793168.208 803695.173),117.191106
4,39057,Greene County,"POLYGON ((1008169.795 1915287.022, 1008161.905...",8,3.14,1.077500,2.712500,13.999125,POINT (1026417.426 1917896.79),7.608318
...,...,...,...,...,...,...,...,...,...,...
3230,53065,Stevens County,"POLYGON ((-1634783.911 2949984.436, -1634792.5...",27,303.67,248.890370,7.285185,134.215963,POINT (-1620086.769 3008995.813),13.406200
3231,19177,Van Buren County,"POLYGON ((319198.812 1994179.49, 319368.793 19...",5,2.34,1.660000,3.240000,0.107800,POINT (339024.413 1978577.566),7.962745
3232,31073,Gosper County,"POLYGON ((-333884.885 1963990.326, -333876.567...",4,12.42,33.357500,8.900000,0.023500,POINT (-321757.583 1951127.058),10.567262
3233,28095,Monroe County,"POLYGON ((712737.052 1232057.495, 712736.922 1...",12,20.16,6.275833,2.883333,22.639000,POINT (689723.121 1230229.636),1.451238
3234,12033,Escambia County,"POLYGON ((796753.93 900693.947, 796753.954 900...",4,2.06,2.297500,3.650000,0.378250,POINT (830688.592 865842.346),7.267296

In [70]:
df_county.drop(columns = ["geometry", "centroid"]).to_csv("../processed_data/lakes_by_county.csv")