In [1]:
import pandas as pd
from pathlib import Path

In [2]:
processed_dir = Path.cwd().parent / "processed_data"
df = pd.read_csv(processed_dir / "final_dataset.csv", index_col=0)
print(f"Total counties: {len(df)}")
df.head()

Total counties: 3235

,geo_id,county_name,population,median_household_income,housing_units,total_energy_consumption_mwh,data_centers_count,sfha_area,pct_sfha,lake_count,...,pga_max,distance_to_lines_km,transmission_lines_count,max_voltage,average_voltage,protected_count,total_protected_area_m,pct_protected,county_area_km2,population_density
0,40075,Kiowa County,8181.0,42679.0,4700.0,157935.0,0.0,2.112674e+08,0.079146,10,...,0.180,16.455467,10.0,138.0,110.400000,2.0,4.108833e+07,0.015393,2669.336760,3.064806
1,46079,Lake County,10993.0,74884.0,5714.0,170505.0,0.0,1.890356e+08,0.126898,48,...,0.051,2.165857,18.0,69.0,69.000000,156.0,1.136746e+08,0.076309,1489.662955,7.379522
2,37033,Caswell County,22563.0,56999.0,10493.0,295896.0,0.0,6.618573e+07,0.059609,4,...,0.082,10.562934,3.0,230.0,230.000000,16.0,1.409890e+07,0.012698,1110.336635,20.320864
3,48377,Presidio County,5433.0,29012.0,3396.0,106309.0,0.0,0.000000e+00,0.000000,0,...,0.150,6.887895,4.0,69.0,69.000000,16.0,3.486332e+08,0.034909,9986.831983,0.544016
4,39057,Greene County,174322.0,81243.0,71471.0,2239244.0,0.0,1.002618e+08,0.092999,8,...,0.097,1.588568,44.0,345.0,112.909091,58.0,1.130754e+07,0.010488,1078.100699,161.693616

In [3]:
# drop counties with high seismic risk
seismic_ok = df["pga_max"] <= 0.3
df = df[seismic_ok]
print(f"{len(df)} counties remaining")

2852 counties remaining

In [4]:
# drop counties where too much land is a flood zone
flood_ok = df["pct_sfha"] <= 0.2
df = df[flood_ok]
print(f"{len(df)} counties remaining")

2515 counties remaining

In [5]:
# drop counties where too much land is military
military_ok = df["pct_military"] <= 0.1
df = df[military_ok]
print(f"{len(df)} counties remaining")

2476 counties remaining

In [6]:
# drop counties where too much land is protected (GAP status 1 or 2)
protected_ok = df["pct_protected"] <= 0.1
df = df[protected_ok]
print(f"{len(df)} counties remaining")

2161 counties remaining

In [7]:
df = df.reset_index(drop=True)
df

,geo_id,county_name,population,median_household_income,housing_units,total_energy_consumption_mwh,data_centers_count,sfha_area,pct_sfha,lake_count,...,pga_max,distance_to_lines_km,transmission_lines_count,max_voltage,average_voltage,protected_count,total_protected_area_m,pct_protected,county_area_km2,population_density
0,40075,Kiowa County,8181.0,42679.0,4700.0,157935.0,0.0,2.112674e+08,0.079146,10,...,0.180,16.455467,10.0,138.0,110.400000,2.0,4.108833e+07,0.015393,2669.336760,3.064806
1,46079,Lake County,10993.0,74884.0,5714.0,170505.0,0.0,1.890356e+08,0.126898,48,...,0.051,2.165857,18.0,69.0,69.000000,156.0,1.136746e+08,0.076309,1489.662955,7.379522
2,37033,Caswell County,22563.0,56999.0,10493.0,295896.0,0.0,6.618573e+07,0.059609,4,...,0.082,10.562934,3.0,230.0,230.000000,16.0,1.409890e+07,0.012698,1110.336635,20.320864
3,48377,Presidio County,5433.0,29012.0,3396.0,106309.0,0.0,0.000000e+00,0.000000,0,...,0.150,6.887895,4.0,69.0,69.000000,16.0,3.486332e+08,0.034909,9986.831983,0.544016
4,39057,Greene County,174322.0,81243.0,71471.0,2239244.0,0.0,1.002618e+08,0.092999,8,...,0.097,1.588568,44.0,345.0,112.909091,58.0,1.130754e+07,0.010488,1078.100699,161.693616
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2156,21079,Garrard County,18207.0,58263.0,7284.0,282164.0,0.0,2.906966e+07,0.047976,1,...,0.120,2.328877,15.0,345.0,92.000000,49.0,1.271817e+07,0.020990,605.917102,30.048665
2157,53065,Stevens County,49668.0,62381.0,22312.0,536848.0,0.0,1.749183e+05,0.000027,27,...,0.150,71.466142,0.0,0.0,0.000000,116.0,2.801182e+08,0.042580,6578.600470,7.549934
2158,19177,Van Buren County,7131.0,58417.0,3509.0,126206.0,0.0,1.457009e+08,0.114681,5,...,0.065,6.011057,8.0,69.0,69.000000,37.0,3.431825e+07,0.027012,1270.486217,5.612812
2159,31073,Gosper County,1803.0,76583.0,1193.0,33218.0,0.0,8.760107e+07,0.073095,4,...,0.043,2.795926,19.0,115.0,93.210526,4.0,8.381496e+06,0.006994,1198.448014,1.504446
2160,12033,Escambia County,333834.0,61642.0,146123.0,3771721.0,0.0,5.182081e+08,0.177738,4,...,0.053,3.436391,47.0,230.0,137.021277,84.0,1.186952e+08,0.040711,2915.576688,114.500161

In [8]:
df.to_csv(processed_dir / "candidates.csv", index=False)